Enable manual deploy of wiki
oppia/oppia-web-developer-docs pull request #114
Opened 2023-02-20 17:00 UTC by gp201

Added `workflow_dispatch` event trigger to allow users to manually run the workflow to deploy the changes.

More info: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

2023-02-20 20:04 UTC, U8NWXD requested changes

2023-02-20 20:04 UTC, U8NWXD commented on Wiki.md
> +### Failed to push changes to wiki upon PR merge.
Can you update the toc?

2023-02-21 05:11 UTC, gp201 commented on Wiki.md
> +### Failed to push changes to wiki upon PR merge.
Done

2023-02-21 05:12 UTC, gp201 commented
@U8NWXD PTAL

2023-02-21 16:02 UTC, U8NWXD approved these changes

2023-02-21 16:02 UTC, merged