Add error [Errno 104] Connection reset by peer
oppia/oppia-web-developer-docs pull request #140
Opened 2023-03-18 13:07 UTC by deadex-ng

This fixes #133 
It also arranges the Table of Contents in alphabetical order to easily navigate through.

2023-03-19 18:09 UTC, U8NWXD requested changes
The table of contents is out of order compared to the rest of the document

2023-03-19 18:34 UTC, gp201 reviewed
1 minor fix

2023-03-19 18:34 UTC, gp201 commented on Troubleshooting.md
> +Then run `pip install "requests[security]"`.
```suggestion
Then run `pip install requests[security]`. 
```

2023-03-25 10:05 UTC, deadex-ng commented on Troubleshooting.md
> +Then run `pip install "requests[security]"`.
I've updated this in the PR.

2023-03-27 14:38 UTC, U8NWXD approved these changes

2023-03-27 14:38 UTC, merged