Updated Apache-Beam-Jobs.md
oppia/oppia-web-developer-docs pull request #151
Opened 2023-03-30 13:08 UTC by PasunuriSrinidhi

Implementation of  error handling in the expand method

2023-03-31 15:40 UTC, U8NWXD requested changes

2023-03-31 15:40 UTC, U8NWXD commented on Apache-Beam-Jobs.md
> +         # add error handling
```suggestion
        # add error handling
```

2023-03-31 15:40 UTC, U8NWXD commented on Apache-Beam-Jobs.md
> +               )
Can you add more discussion of what this does, and how it handles errors?

2023-07-02 18:31 UTC, Ash-2k3 commented
@PasunuriSrinidhi Are you interested in completing this PR, if yes please let me know my replying to this comment. Thanks

2023-07-17 01:30 UTC, U8NWXD commented
Closing due to inactivity

2023-07-17 01:30 UTC, closed without merging