Update LaCE-onboarding-guide.md
oppia/oppia-web-developer-docs pull request #170
Opened 2023-05-24 18:45 UTC by prafulbbandre

Fix the typos of LaCE-onboarding-guide.md

2023-05-29 12:08 UTC, gp201 commented
@prafulbbandre is this PR ready to be reviewed?

2023-05-29 12:25 UTC, prafulbbandre commented
@gp201 i am going to add more info(screenshot) to it. I will let you know when it's ready.

2023-06-06 17:55 UTC, seanlip approved these changes
Thanks @prafulbbandre! No concerns from my end.

2023-06-10 04:53 UTC, gp201 requested changes
Thanks, @prafulbbandre ! I left some comments. PTAL

2023-06-10 04:53 UTC, gp201 commented on LaCE-onboarding-guide.md
> +![Activities Tab](https://github.com/prafulbbandre/oppia-web-developer-docs/assets/109658545/39a77f42-c38b-4f5b-9bd9-29366ab8bcb8)
All the images seems to be linked to your fork. Can you move them to the oppia/oppia-web-developer-docs repo?

2023-06-13 07:06 UTC, gp201 commented
Can you combine #173 with #170 ?

2023-06-13 18:12 UTC, prafulbbandre commented
It's combined in #173

2023-06-13 18:12 UTC, closed without merging