[GSoC'23] M1.5 - Oppia Docker setup Installation Guide
oppia/oppia-web-developer-docs pull request #179
Opened 2023-07-17 19:15 UTC by shivkant5

This PR contains the Installation Guide for the Dockerized Oppia development server, including information regarding all the make commands.
Refer - https://github.com/oppia/oppia/issues/18257

2023-07-18 13:38 UTC, U8NWXD requested changes

2023-07-18 13:38 UTC, U8NWXD commented on .DS_Store
please remove this file

2023-07-18 13:38 UTC, U8NWXD commented on Installing-Oppia-Docker.md
> +# **Dockerized Oppia Installation Guide**
The wiki automatically generates a title based on the filename (in this case it'll be "Installing Oppia Docker"), so you don't need this

2023-07-18 13:38 UTC, U8NWXD commented on Installing-Oppia.md
> +
I think we should be clearer about what the difference is between the installation approaches from the developer's perspective. How about we label the Python setup as "standard" and the Docker setup as "experimental"? Then once we're sure the Docker setup is stable, we can make it "standard".

2023-07-18 13:38 UTC, U8NWXD commented on Installing-Oppia-Docker.md
> +* Additional Make Commands
These should be links to the relevant sections

2023-07-18 13:38 UTC, U8NWXD commented on Installing-Oppia-Docker.md
> +> NOTE: The above 2 steps need to be followed only once. The next time you want to run Oppia, you can directly start from the next section, i.e. by executing simple `make` commands from the root dire
```suggestion
> NOTE: The above step needs to be followed only once. The next time you want to run Oppia, you can directly start from the next section, i.e. by executing simple `make` commands from the root directory of the cloned Oppia repository.
```

2023-07-18 13:38 UTC, U8NWXD commented on Installing-Oppia-Docker.md
> +2. **Build Oppia for the First Time**: Run the following command to build Oppia for the first time. This step downloads all the necessary third-party libraries, python dependencies, and the other ser
```suggestion
2. **Build Oppia for the First Time**: Run the following command to build Oppia for the first time. This step downloads all the necessary third-party libraries, python dependencies, and the other services required for the Oppia development server, which may take approximately 15-20 minutes (varies according to the network connection speed).
```

2023-07-18 13:38 UTC, U8NWXD commented on Installing-Oppia-Docker.md
> +- `save_datastore`: This flag saves donot clear the datastore on shutting down the development server.
```suggestion
- `save_datastore`: This flag prevents clearing of the datastore upon shutting down the development server.
```

2023-07-18 13:38 UTC, U8NWXD commented on Installing-Oppia-Docker.md
> +- `disable_host_checking`: It disables host checking so that the dev server can be accessed by any device on the same network using the host device's IP address. DO NOT use this flag if you're runnin
```suggestion
- `disable_host_checking`: Disables host checking so that the dev server can be accessed by any device on the same network using the host device's IP address. DO NOT use this flag if you're running on an untrusted network.
```

Avoid starting these descriptions with "it". You can use "This flag" instead or just leave "it" out entirely. ditto elsewhere

2023-07-18 13:38 UTC, U8NWXD commented on Installing-Oppia-Docker.md
> +The Oppia development environment provides additional `make` commands that you can use for various purposes. The following lists the available `make` commands and their descriptions --
```suggestion
The Oppia development environment provides additional `make` commands that you can use for various purposes. The following lists the available `make` commands and their descriptions:
```

2023-07-18 13:38 UTC, U8NWXD commented on Installing-Oppia-Docker.md
> +- `make clean`: This command cleans the Oppia development environment (under Docker) by removing all the docker containers, images, and volumes.
add `run-offline` to this list

2023-07-18 13:38 UTC, U8NWXD commented on Installing-Oppia-Docker.md
> +That's it! You have successfully installed Oppia using Docker, and ready-to-go for your contributions at Oppia.
I think this should go just before the "Using Flags with Make Command" sections

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on Installing-Oppia-Docker.md
> +# **Dockerized Oppia Installation Guide**
removed

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on Installing-Oppia-Docker.md
> +> NOTE: The above 2 steps need to be followed only once. The next time you want to run Oppia, you can directly start from the next section, i.e. by executing simple `make` commands from the root dire
done

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on Installing-Oppia-Docker.md
> +2. **Build Oppia for the First Time**: Run the following command to build Oppia for the first time. This step downloads all the necessary third-party libraries, python dependencies, and the other ser
done

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on Installing-Oppia-Docker.md
> +- `save_datastore`: This flag saves donot clear the datastore on shutting down the development server.
done

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on Installing-Oppia-Docker.md
> +- `disable_host_checking`: It disables host checking so that the dev server can be accessed by any device on the same network using the host device's IP address. DO NOT use this flag if you're runnin
done

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on Installing-Oppia-Docker.md
> +The Oppia development environment provides additional `make` commands that you can use for various purposes. The following lists the available `make` commands and their descriptions --
done

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on Installing-Oppia-Docker.md
> +That's it! You have successfully installed Oppia using Docker, and ready-to-go for your contributions at Oppia.
done

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on Installing-Oppia.md
> +
please check if this is fine?

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on Installing-Oppia-Docker.md
> +* Additional Make Commands
done

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on Installing-Oppia-Docker.md
> +- `make clean`: This command cleans the Oppia development environment (under Docker) by removing all the docker containers, images, and volumes.
added all new make commands! please check

2023-07-19 22:20 UTC, Shivkant-Chauhan commented on .DS_Store
done

2023-07-20 03:08 UTC, U8NWXD approved these changes

2023-07-20 03:15 UTC, U8NWXD commented
Looks great! Let's wait to merge this until the flags PR is in

2023-07-21 12:43 UTC, merged