Fix #48 : Add Typescript tutorial
oppia/oppia-web-developer-docs pull request #190
Opened 2023-08-14 05:41 UTC by MohitGupta121

Fix #48 : Add Typescript tutorial

2023-08-14 05:42 UTC, MohitGupta121 commented
@Ash-2k3 PTAL, Please have initial review after that pass next review to lead. Thanks!

2023-08-14 16:42 UTC, U8NWXD requested changes

2023-08-14 16:42 UTC, U8NWXD commented on Learning-Resources.md
> +    * Checkout the great TypeScript [tutorial](https://www.freecodecamp.org/news/learn-typescript-beginners-guide/)
```suggestion
    * Check out this TypeScript [tutorial](https://www.freecodecamp.org/news/learn-typescript-beginners-guide/).
```

To stay consistent with the rest of the page

2023-08-14 17:03 UTC, MohitGupta121 commented on Learning-Resources.md
> +    * Checkout the great TypeScript [tutorial](https://www.freecodecamp.org/news/learn-typescript-beginners-guide/)
Done.

2023-08-14 17:03 UTC, MohitGupta121 reviewed
@U8NWXD PTAL, changes applied, Thanks!

2023-08-14 17:15 UTC, Ash-2k3 approved these changes
Thanks @MohitGupta121, LGTM.

2023-08-16 13:08 UTC, U8NWXD approved these changes

2023-08-16 13:08 UTC, merged