Adds missing codeblock in Installing Oppia for Linux Documentation
oppia/oppia-web-developer-docs pull request #231
Opened 2024-01-07 14:55 UTC by LalitChauhan56

Fixes #230 
This PR adds the missing codeblock as discussed in #230.

2024-01-07 15:59 UTC, seanlip commented
Hi @LalitChauhan56, thanks for your PR. Please follow the instructions here first though, we need a CLA to accept contributions: https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up. Thanks.

2024-01-07 16:30 UTC, LalitChauhan56 commented
Hi @seanlip sorry for missing such an important step. I just signed the CLA. Should this PR be reopened or should I open a new one?

2024-01-07 17:43 UTC, seanlip commented
We can reopen it, thanks.

2024-01-07 17:44 UTC, seanlip requested changes

2024-01-07 17:44 UTC, seanlip commented on Installing-Oppia-(Linux;-Python-3).md
> +    ```sudo apt-get install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblz
Could you also ensure that this is properly displayed indented, under point "1", and similarly for the stuff in point 2? Currently the code blocks and the second paragraph of point 2 jut out into the left margin.

2024-01-07 18:17 UTC, LalitChauhan56 commented
![image](https://github.com/oppia/oppia-web-developer-docs/assets/73524110/eb51e4f4-dc94-4b92-b718-ae1b900d6107)

I think this fixes the indentation issue.

2024-01-07 20:36 UTC, seanlip approved these changes
LGTM. Thanks!

2024-01-07 20:41 UTC, merged

2024-01-07 20:42 UTC, seanlip commented
(And congrats on your first PR to Oppia :) )

2024-01-08 00:47 UTC, LalitChauhan56 commented
> (And congrats on your first PR to Oppia :) )

Thank you for helping me out! :)