link update
oppia/oppia-web-developer-docs pull request #304
Opened 2024-04-04 03:00 UTC by rahat2134

Fix #303

2024-04-04 03:01 UTC, rahat2134 commented
@seanlip PTAL

2024-04-08 21:29 UTC, rahat2134 commented
@seanlip PTAL.

2024-04-09 01:33 UTC, seanlip requested changes
Hi @rahat2134, thanks, just one comment!

2024-04-09 01:33 UTC, seanlip commented on End-to-End-Tests.md
> +For information on writing tests with webdriverio, see the [webdriverio's documentation](https://webdriver.io/docs/gettingstarted). If you need to work out why your tests aren't working, check out ou
Thanks @rahat2134. Could you use the existing format: [[debugging guide for E2E tests|Debug-end-to-end-tests]] ?

2024-04-09 08:37 UTC, rahat2134 commented on End-to-End-Tests.md
> +For information on writing tests with webdriverio, see the [webdriverio's documentation](https://webdriver.io/docs/gettingstarted). If you need to work out why your tests aren't working, check out ou
Done

2024-04-09 11:48 UTC, seanlip commented on End-to-End-Tests.md
> +For information on writing tests with webdriverio, see the [webdriverio's documentation](https://webdriver.io/docs/gettingstarted). If you need to work out why your tests aren't working, check out ou
No, you haven't done what I asked. For internal wiki link pages, you don't need the github.com/oppia/oppia/wiki/ prefix. (Have a look at what it was before.)

2024-04-09 12:44 UTC, rahat2134 commented on End-to-End-Tests.md
> +For information on writing tests with webdriverio, see the [webdriverio's documentation](https://webdriver.io/docs/gettingstarted). If you need to work out why your tests aren't working, check out ou
sorry! Done Now. 
`[[debugging guide for E2E tests|Debug-end-to-end-tests]]`

2024-04-09 12:49 UTC, seanlip approved these changes
Thanks!

2024-04-09 12:49 UTC, merged