Error: File not found while running python -m scripts.start
oppia/oppia-web-developer-docs pull request #313
Opened 2024-04-18 18:02 UTC by hrshkshri

Issue #207 

Discussion https://github.com/oppia/oppia/discussions/16281#discussioncomment-3863892

2024-04-18 18:10 UTC, Ash-2k3 requested changes
Thanks @hrshkshri! Can you please add instructions for other errors as well which are mentioned in the issue description ?

2024-04-20 07:45 UTC, hrshkshri commented
> Thanks @hrshkshri! Can you please add instructions for other errors as well which are mentioned in the issue description ?

Hey @Ash-2k3 
About the https://github.com/oppia/oppia/discussions/17511#discussioncomment-5125522 which is mentioned in the issue description, we already have this [wiki](https://github.com/oppia/oppia/discussions/17511#discussioncomment-5125522) to address the discussion mentioned above. PTAL

2024-04-21 11:34 UTC, Ash-2k3 commented
@hrshkshri, let's add this in our FAQs page then, so that it can get some more visibility. Also what about other linked discussions in the issue thread ? I would suggest to add them to either our FAQs wiki or troubleshoot wiki accordingly.
One thing to check would be if there is already something similar in either of those pages (To make sure we are not adding same thing again n again.)

2024-04-22 19:23 UTC, Ash-2k3 requested changes
My previous comment still applies -- I still don't see all of the linked Github discussion's solution here.

Please cross check properly before asking for a further review. Thanks!

2024-04-23 00:34 UTC, hrshkshri commented
> My previous comment still applies -- I still don't see all of the linked Github discussion's solution here.
> 
> Please cross check properly before asking for a further review. Thanks!

Ahh, @Ash-2k3 
Sorry, I thought the discussions which are opened needed to be updated (Updating all of them rn)

Thanks

2026-02-19 10:21 UTC, HardikGoyal2003 commented
Closing this PR due to inactivity.

2026-02-19 10:21 UTC, closed without merging