Fixes Part of #331: Moved Pre-requisites before Installation in Docker Installation
oppia/oppia-web-developer-docs pull request #332
Opened 2024-06-22 03:54 UTC by jayam04

2024-06-22 03:56 UTC, jayam04 commented
@seanlip PTAL

2024-06-27 03:45 UTC, jayam04 commented
@seanlip PTAL

2024-06-27 07:04 UTC, seanlip requested changes
Thanks @jayam04. There seems to be quite a bit more in this PR than what was stated in the description; can you update the description?

Also I left a comment, PTAL, thanks.

2024-06-27 07:04 UTC, seanlip commented on Installing-Oppia-using-Docker.md
> +	* `--prod_env` - Run acceptance test in mobile viewport
This doesn't make sense, was this change intended?

2024-06-29 06:52 UTC, jayam04 commented
@seanlip Updated Description and fixed suggestion. PTAL.

2024-07-23 17:40 UTC, jayam04 commented
@seanlip Can you PTAL.

2024-07-24 07:12 UTC, seanlip approved these changes
Sorry for the late reply! LGTM.

Also, just a note, next time please assign me if you want a review (i.e. make sure my GitHub username is under the Assignees section). Thanks!

2024-07-24 07:12 UTC, merged

2024-07-24 07:17 UTC, jayam04 commented
@seanlip I am aware that we should assign PR to reviewers, when review is required. I try to make sure of it, but I don't have privileges to assign people in web-docs repo.

2024-07-24 07:40 UTC, seanlip commented
Ah sorry, I think that was a configuration issue. You should have permissions now, I think?