Initial Draft
oppia/oppia-web-developer-docs pull request #388
Opened 2024-09-16 01:13 UTC by Ash-2k3

2024-09-17 04:00 UTC, Ash-2k3 commented
Hey @U8NWXD, PTAL at this PR, thanks!

2024-09-22 02:12 UTC, U8NWXD requested changes

2024-09-22 02:12 UTC, U8NWXD commented on Tutorial:-Learn-How-to-Write-and-Test-a-Non-Trivial-Beam-Job.md
Please add a table of contents. Instructions and format here: https://github.com/oppia/oppia/wiki/Wiki-style-guide#writing-style

2024-09-27 12:37 UTC, Ash-2k3 commented on Tutorial:-Learn-How-to-Write-and-Test-a-Non-Trivial-Beam-Job.md
Done, PTAL.Thanks!

2024-10-02 00:52 UTC, U8NWXD requested changes
Great, thanks! One last thing--can you add this page to the sidebar (in `_Sidebar.md`) in the location we planned out in the google doc? sorry I missed this before

2024-10-03 13:23 UTC, Ash-2k3 commented
> Great, thanks! One last thing--can you add this page to the sidebar (in `_Sidebar.md`) in the location we planned out in the google doc? sorry I missed this before

Done, PTAL, Thanks!

2024-10-03 13:24 UTC, Ash-2k3 commented on _Sidebar.md
> +        * [[Tutorial - Learn to write and test a non-trivial Beam job|Tutorial:-Learn-How-to-Write-and-Test-a-Non-Trivial-Beam-Job]]
Reference: https://docs.google.com/document/d/1W6r4AW7WOP5MzJhoRKRS73IhXLj-KKo3_HDRRWHg2D4/edit (Sidebar Wiki Doc)

2024-10-06 18:38 UTC, U8NWXD approved these changes

2024-10-06 18:40 UTC, merged