update adding new page.md
oppia/oppia-web-developer-docs pull request #39
Opened 2022-10-03 20:23 UTC by sanil011

2022-10-31 03:32 UTC, U8NWXD requested changes

2022-10-31 03:32 UTC, U8NWXD commented on Actions-and-issues.md
> +We store the steps a user takes through exploration as _actions_, and we create _issues_ to keep track of the problems that these actions indicate. Both actions and issues are defined as [[schemas|Sc
I think the `an` is correct here

2022-10-31 03:32 UTC, U8NWXD commented on Actions-and-issues.md
> +There are three actions defined as [`extensions/actions/`](https://github.com/oppia/oppia/tree/develop/extensions/actions):
I think `at` is correct here because the actions are defined inside the `actions` folder, not by the folder itself

2022-10-31 03:32 UTC, U8NWXD commented on Adding-new-page.md
> +into `ci.collect.assert.assertMatrix`.
What's being changed here?

2022-12-13 00:37 UTC, gp201 commented
@sanil011 If you need help or clarification anywhere, feel free to ask us.

2022-12-15 20:39 UTC, gp201 commented
@sanil011 Could you please respond to this within 3 days, otherwise, we'll close this PR as inactive.

2022-12-18 22:50 UTC, gp201 commented
Closing since there is no response from the contributor.

2022-12-18 22:50 UTC, closed without merging