DRAFT for E2E test tutorial
oppia/oppia-web-developer-docs pull request #401
Opened 2024-11-03 18:29 UTC by Ash-2k3

2024-11-10 21:18 UTC, U8NWXD requested changes

2024-11-10 21:18 UTC, U8NWXD commented on Tutorial-Learn-How-to-Fix-a-CI-Flake-waitFor-Statements
You're missing a `.md` at the end of this file. Please fix that so I can see the rendered Markdown

2024-11-10 21:22 UTC, U8NWXD commented
Also, don't forget to add the tutorial to the sidebar in this PR

2024-11-13 08:26 UTC, Ash-2k3 commented
Hi @U8NWXD, I have addressed your comments, PTAL, Thanks!

2024-11-13 08:27 UTC, Ash-2k3 commented on Tutorial-Learn-How-to-Fix-a-CI-Flake-waitFor-Statements
Ah sorry, I have fixed it, PTAL!

2024-11-17 18:03 UTC, U8NWXD approved these changes

2024-11-17 18:03 UTC, merged