Draft PR for tutorial on new feature
oppia/oppia-web-developer-docs pull request #402
Opened 2024-11-06 12:32 UTC by Ash-2k3

2024-11-10 21:21 UTC, U8NWXD requested changes
Please also add this tutorial to the sidebar

2024-11-10 21:21 UTC, U8NWXD commented on Tutorial-Learn-How-to-Add-a-New-Feature.md
> +- Set up your development environment. (If you haven't, follow the [Oppia setup instructions](https://github.com/oppia/oppia/wiki/End-to-End-Tests)).
I think this is the wrong link?

2024-11-13 08:20 UTC, Ash-2k3 commented on Tutorial-Learn-How-to-Add-a-New-Feature.md
> +- Set up your development environment. (If you haven't, follow the [Oppia setup instructions](https://github.com/oppia/oppia/wiki/End-to-End-Tests)).
Fixed, thanks for catching

2024-11-13 08:20 UTC, Ash-2k3 commented
Hi @U8NWXD, I have addressed your comments, PTAL!

2024-11-15 01:14 UTC, U8NWXD approved these changes

2024-11-15 01:15 UTC, merged