Update our debugging instructions.
oppia/oppia-web-developer-docs pull request #406
Opened 2024-11-15 15:47 UTC by seanlip

This PR attempts to streamline and simplify our debugging instructions, in particular, clarifying the instructions for what to do in the event of an error in the CI checks.

2024-12-02 13:19 UTC, seanlip commented on Debugging-Docs.md
> -## Examples
Note: I moved these to the debugging doc template.

2024-12-03 01:47 UTC, U8NWXD requested changes

2024-12-03 01:47 UTC, U8NWXD commented on If-CI-checks-fail-on-your-PR.md
> +  ![GHCI Status](images/ghciSample.png)
"GHCI Status" might be confusing as alt text. Maybe "Screenshot of CI results on GitHub"?

2024-12-03 01:47 UTC, U8NWXD commented on If-CI-checks-fail-on-your-PR.md
> +  ![GHCI Logs](images/githubActionsLogs.png)
ditto for more informative alt text

2024-12-03 02:03 UTC, seanlip commented on If-CI-checks-fail-on-your-PR.md
> +  ![GHCI Status](images/ghciSample.png)
Done.

2024-12-03 02:03 UTC, seanlip commented on If-CI-checks-fail-on-your-PR.md
> +  ![GHCI Logs](images/githubActionsLogs.png)
Done.

2024-12-03 02:05 UTC, seanlip commented
Thanks @U8NWXD! Fixed, PTAL.

2024-12-07 18:51 UTC, U8NWXD approved these changes

2024-12-07 18:51 UTC, merged