Milestone 2.7: Remove documentation related to protractor.
oppia/oppia-web-developer-docs pull request #41
Opened 2022-10-05 12:21 UTC by ShivamJhaa

This PR removed the following documentation:
* Hybrid State
* Guide to migrate end to end tests
* Debug End to End tests in protractor
* End to End tests in protractor

2022-10-09 05:25 UTC, U8NWXD requested changes
just one nit

2022-10-09 05:25 UTC, U8NWXD commented on Debug-custom-ESLint-check-tests.md
> +        $('.webdriverio-test')).setValue("keys");
Isn't this now `.e2e-test`?

2022-10-09 06:38 UTC, SAEb-ai approved these changes
Except U8NWXD's comment above, LGTM. Thanks and congratulations for completing the full migration finally.

2022-10-09 06:48 UTC, ShivamJhaa commented on Debug-custom-ESLint-check-tests.md
> +        $('.webdriverio-test')).setValue("keys");
Yes, corrected.

2022-10-09 06:48 UTC, ShivamJhaa commented
@U8NWXD PTAL, thanks!

2022-10-09 06:50 UTC, ShivamJhaa commented
> Except U8NWXD's comment above, LGTM. Thanks and congratulations for completing the full migration finally.

Thanks @SAEb-ai .

2022-10-10 04:31 UTC, U8NWXD approved these changes

2022-10-10 04:31 UTC, merged