Draft tutorial on debugging docs
oppia/oppia-web-developer-docs pull request #421
Opened 2024-12-02 13:08 UTC by Ash-2k3

2024-12-08 18:42 UTC, U8NWXD requested changes

2024-12-08 18:42 UTC, U8NWXD commented on Tutorial-Learn-to-Debug-an-Issue-Using-a-Debugging-Doc.md
> +2. **Apply the Patch File:** Download the patch file from the [provided link](https://drive.google.com/file/d/1aTPrkslSg5nyc6e8BVEks-KGqlkACHjI/view) and apply it to your local branch: `git apply /pa
can we put the patch file in the wiki repository instead? That way we keep the wiki assets together like we do with images

2024-12-15 16:32 UTC, Ash-2k3 commented on patchFiles/tutorial-debugging-doc-setup.patch
@U8NWXD I have added the patch file like this but please let me know if you have better suggestions on where to add this. Thanks!

2024-12-15 18:15 UTC, U8NWXD approved these changes

2024-12-15 18:15 UTC, merged