Change job running instructions
oppia/oppia-web-developer-docs pull request #46
Opened 2022-10-19 14:19 UTC by vojtechjelinek

As we came up with new backup server admins policies we are also updating the wiki to reflect those policies.

2022-10-20 08:17 UTC, seanlip requested changes
Thanks! Took a pass.

2022-10-20 08:17 UTC, seanlip commented on Testing-jobs-and-other-features-on-production.md
> +Also, in case your job is a new migration job (not any already existing migrations), there has to be an audit job accompanying it to verify that the data that you are migrating are valid in the serve
Keep it as "is" -- data is actually plural. (The singular is datum.)

Also change "any" to "an" in the parenthetical.

2022-10-20 08:17 UTC, seanlip commented on Testing-jobs-and-other-features-on-production.md
> +The form responses go to the server jobs admins and the admins should respond to the contributor within 24 hours. The server jobs admin should send updates after running the job(s) to the job author
should send --> will send
should approve --> will approve
Delete extra space between "job(s)" and "in".

2022-10-20 08:18 UTC, seanlip commented
@vojtechjelinek please remember to use the assignees field, not the reviewers field. Thanks!

2022-10-20 09:43 UTC, vojtechjelinek commented
@seanlip Yeah, I cannot change the assignees on this repo.

2022-10-20 21:40 UTC, kevintab95 approved these changes
Thanks for doing this Vojta. LGTM!

2022-10-21 04:26 UTC, DubeySandeep approved these changes

2022-10-21 05:53 UTC, seanlip approved these changes
Thanks @vojtechjelinek !

2022-10-21 05:53 UTC, merged