Fixes(#61): Adds backend code coverage reference
oppia/oppia-web-developer-docs pull request #70
Opened 2022-12-22 11:14 UTC by Nik-09

Adds the reference link of backend code coverage in the `Debugging backend test` wiki.

2022-12-22 11:15 UTC, Nik-09 commented
Hi @U8NWXD PTAL, once you are free.
Thank you.

2022-12-27 17:59 UTC, gp201 requested changes
Thanks, @Nik-09 ! I left some comments. PTAL

2022-12-27 17:59 UTC, gp201 commented on Debug-backend-tests.md
> +For identifying the missing coverage lines run the below command.
```suggestion
To identify the missing coverage lines, run the below command.
```

2022-12-27 17:59 UTC, gp201 commented on Debug-backend-tests.md
> +For identifying the missing coverage lines run the below command.
```suggestion
To identify the missing coverage lines, run the below command.
```

2022-12-27 17:59 UTC, gp201 commented on Debug-backend-tests.md
> +For identifying the missing coverage lines run the below command.
```suggestion
To identify the missing coverage lines, run the below command.
```

2022-12-27 17:59 UTC, gp201 commented on Debug-backend-tests.md
> +For more understanding about the backend code coverage kindly refer [here](https://github.com/oppia/oppia/wiki/Backend-tests#coverage-reports).
```suggestion
For more information about the backend code coverage, kindly refer [here](https://github.com/oppia/oppia/wiki/Backend-tests#coverage-reports).
```

2022-12-27 17:59 UTC, gp201 commented on Debug-backend-tests.md
> +For more understanding about the backend code coverage kindly refer [here](https://github.com/oppia/oppia/wiki/Backend-tests#coverage-reports).
```suggestion
For more information about the backend code coverage, kindly refer [here](https://github.com/oppia/oppia/wiki/Backend-tests#coverage-reports).
```

2022-12-27 17:59 UTC, gp201 commented on Debug-backend-tests.md
> +For more understanding about the backend code coverage kindly refer [here](https://github.com/oppia/oppia/wiki/Backend-tests#coverage-reports).
```suggestion
For more information about the backend code coverage, kindly refer [here](https://github.com/oppia/oppia/wiki/Backend-tests#coverage-reports).
```

2022-12-27 17:59 UTC, gp201 commented on Debug-backend-tests.md
> +For more understanding about the backend code coverage kindly refer [here](https://github.com/oppia/oppia/wiki/Backend-tests#coverage-reports).
```suggestion
For more information about the backend code coverage, kindly refer [here](https://github.com/oppia/oppia/wiki/Backend-tests#coverage-reports).
```

2022-12-28 06:25 UTC, Nik-09 commented on Debug-backend-tests.md
> +For identifying the missing coverage lines run the below command.
Updated

2022-12-28 06:25 UTC, Nik-09 commented on Debug-backend-tests.md
> +For more understanding about the backend code coverage kindly refer [here](https://github.com/oppia/oppia/wiki/Backend-tests#coverage-reports).
Updated

2022-12-28 06:26 UTC, Nik-09 reviewed
Hi, @gp201 I have addressed the comments, PTAL.
Thank you.

2022-12-29 22:43 UTC, gp201 approved these changes
LGTM

2022-12-29 22:43 UTC, merged