Fix#56: Add a Contributor Dashboard info page to wiki for new contributors.
oppia/oppia-web-developer-docs pull request #80
Opened 2023-01-11 23:28 UTC by sagangwee

2023-01-11 23:31 UTC, sagangwee commented
@seanlip PTAL, thanks!

2023-01-12 04:45 UTC, seanlip requested changes
Thanks @sagangwee! Looks fantastic, just two minor notes.

2023-01-12 04:45 UTC, seanlip commented on Contributor-dashboard.md
> +1. Every piece of text content in the lesson does not yet have an accepted translation.
This sounds like the entire lesson is untranslated. Maybe instead: "There is at least one piece of text content in the lesson that does not yet have an accepted translation." ?

2023-01-12 04:45 UTC, seanlip commented on Contributor-dashboard.md
> +1. [Contributor dashboard overview](https://docs.google.com/document/d/1wM9cQzq1-3nbEhZliRlpnGDXbM_HspNkY16CYnA6lWg/edit#): More in-depth developer focused overview of the backend structure of the co
Just a heads-up that there's an unresolved comment in this doc.

2023-01-12 10:47 UTC, seanlip commented
@sagangwee I just had an idea -- what do you think about adding one or two simple exercises to this doc to help contributors verify that they've got things set up and can make changes? E.g. ask them to add a label to the right of each reviewer's name, or add a date to the card, or something simple like that, and show a screenshot of what they should see on their local machine.

This could help potential contributors get a feel for the ins and outs of the dashboard, and can also give you a check when accepting someone new to the team (you can ask for a screenshot of that toy project). Thoughts?

2023-01-12 20:22 UTC, sagangwee commented
@seanlip Ah, that reminds me—I forgot to add relevant code pointers with corresponding screenshots of the UI where applicable. I think once I add those, that should be enough for a new contributor to get their bearings.

2023-01-12 23:16 UTC, sagangwee reviewed
@seanlip Addressed your comments, thanks!

2023-01-12 23:16 UTC, sagangwee commented on Contributor-dashboard.md
> +1. Every piece of text content in the lesson does not yet have an accepted translation.
Ah, yup. That reads better. Thanks. Done.

2023-01-12 23:16 UTC, sagangwee commented on Contributor-dashboard.md
> +1. [Contributor dashboard overview](https://docs.google.com/document/d/1wM9cQzq1-3nbEhZliRlpnGDXbM_HspNkY16CYnA6lWg/edit#): More in-depth developer focused overview of the backend structure of the co
Ack. I'll work on updating that.

2023-01-13 02:59 UTC, seanlip commented
> @seanlip Ah, that reminds me—I forgot to add relevant code pointers with corresponding screenshots of the UI where applicable. I think once I add those, that should be enough for a new contributor to get their bearings.

Ack, looks good, but how about adding an exercise as well? The reason I say this is because while the code pointers help folks find where to look for, they'd probably need to do something small to get a feel for the "flow" of data through the various components. 

So I would suggest adding a paragraph with the smallest "feature" you can think of that illustrates that and suggest that they optionally try working through it as a tutorial -- you can show them a screenshot of what they should see if they successfully get it running, and explain how to test their work. If people get stuck with that, then they'll post on GitHub Discussions and it'll help us get a sense of where the onboarding blockers are. Wdyt?

(Otherwise, everything here looks great, thanks!)

2023-01-17 08:09 UTC, seanlip commented
@sagangwee Can we get this in? It might be useful for #16740 on the main repo.

2023-01-17 23:35 UTC, sagangwee commented
@seanlip Sorry, was not able to get to this today. Will address tomorrow!

2023-01-18 22:58 UTC, sagangwee reviewed
@seanlip Added a sample coding exercise. PTAL, thanks!

2023-01-19 06:14 UTC, seanlip approved these changes
It looks great, thanks @sagangwee!

Could you please remove the .DS_Store that seems to have been included accidentally? Then let's get this merged :) Thanks!

2023-01-19 16:29 UTC, merged

2023-01-19 16:30 UTC, seanlip commented
Merged. Thanks @sagangwee!