Updates instruction for windows.
oppia/oppia-web-developer-docs pull request #82
Opened 2023-01-12 13:34 UTC by Nik-09

This PR updates the instruction to manually start the browser and then access the Oppia localhost.
Referred issue: https://github.com/oppia/oppia/issues/15952

2023-01-12 15:05 UTC, U8NWXD commented
To fix oppia/oppia#15952, I think we need to change the `start.py` code, not the docs. See https://github.com/oppia/oppia/issues/15952#issuecomment-1380520464

2023-01-12 21:27 UTC, gp201 requested changes
Thanks, @Nik-09 ! I left some comments. PTAL

2023-01-12 21:27 UTC, gp201 commented on Installing-Oppia-(Windows;-Python-3).md
> +Navigate to any of the browsers and access Oppia at http://localhost:8181.
Are we listing the browsers anywhere? otherwise can you change it to `Navigate to any browser and access Oppia at http://localhost:8181.
`

2023-01-23 14:33 UTC, Nik-09 commented on Installing-Oppia-(Windows;-Python-3).md
> +Navigate to any of the browsers and access Oppia at http://localhost:8181.
Updated

2023-01-25 02:10 UTC, U8NWXD approved these changes

2023-01-25 02:11 UTC, U8NWXD commented
Merging since @gp201's comments have been addressed

2023-01-25 02:11 UTC, merged